import Link from "next/link";
import Head from "next/head";
import styles from "@/styles/style.module.css";

export default function Navbar() {
  return (
    <>
      <Head>
        <title>Kitchen Pal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../../favicon.png" />
      </Head>
      <nav className={styles.nav}>
        <div className={styles.navbrand}>
          <img src="/logo.png" alt="" />
        </div>
        <div className={styles.navlinks}>
          <Link className={styles.selected} href="../">
            Home
          </Link>
          <Link className={styles.links} href="../recipe">
            Our Recipes
          </Link>
          <Link className={styles.links} href="../aboutus">
            About Us
          </Link>
          <Link className={styles.links} href="/contactus">
            Contact
          </Link>
        </div>
      </nav>
    </>
  );
}
