import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/style.module.css";
import Navbar from "./components/navbar";
import Carousel from "./components/carousel";
import Link from "next/link";
import Footer from "./components/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kitchen Pal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Carousel />
      <div className={styles.home_title}>
        <div className={styles.home_container}>
          <Link className={styles.title} href="../recipe">
            Our Recipe
          </Link>
        </div>
      </div>
      <section className={styles.Recipe_box}>
        <a className={styles.box}>
          <img src="/recipeimg.jpg" alt="" />
          <h5 className={styles.recipie_title}>Spaghetti Carbonara</h5>
          <h6>15 mins</h6>
        </a>
        <a className={styles.box}>
          <img src="/recipeimg.jpg" alt="" />
          <h5 className={styles.recipie_title}>Spaghetti Carbonara</h5>
          <h6>15 mins</h6>
        </a>
        <a className={styles.box}>
          <img src="/recipeimg.jpg" alt="" />
          <h5 className={styles.recipie_title}>Spaghetti Carbonara</h5>
          <h6>15 mins</h6>
        </a>
        <a className={styles.box}>
          <img src="/recipeimg.jpg" alt="" />
          <h5 className={styles.recipie_title}>Spaghetti Carbonara</h5>
          <h6>15 mins</h6>
        </a>
      </section>
      <Footer />
    </>
  );
}
